name: CD2VPS-toumlilt.com
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test ] # TODO: change to master ...

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CI Build first
      uses: ./.github/workflows/ci.yml
    - name: Deploy prod using ssh
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        ARGS: "-rltgoDzvO" # "-avzr --delete"
        SOURCE: "dist-prod/"
        TARGET: ${{ secrets.REMOTE_TARGET }}
        EXCLUDE: ""
        # script: |
        #   cd ~/
        #   git pull origin master
        #   git status