name: CI-toumlilt.com
on: [push]
jobs:
  build-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build prod app
        run: make build-prod
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Build prod app
        run: make build-dev