name: CD2VPS-dev.toumlilt.com
on:
  push:
    branches: [ dev ]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: CI Build first
      uses: ./.github/workflows/ci.yml
    - name: Deploy prod using ssh
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
        ARGS: "-rltgoDzvO" # "-avzr --delete"
        SOURCE: "dist-dev/"
        TARGET: ${{ secrets.REMOTE_DEV_TARGET }}
        EXCLUDE: ""